/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryPie: typeof import('./src/components/stats/CategoryPie.vue')['default']
    NumberKeyboard: typeof import('./src/components/lock/NumberKeyboard.vue')['default']
    PlaceCard: typeof import('./src/components/map/PlaceCard.vue')['default']
    PlaceForm: typeof import('./src/components/place/PlaceForm.vue')['default']
    RatingBar: typeof import('./src/components/stats/RatingBar.vue')['default']
    RatingStar: typeof import('./src/components/review/RatingStar.vue')['default']
    ReviewCard: typeof import('./src/components/review/ReviewCard.vue')['default']
    ReviewFull: typeof import('./src/components/review/ReviewFull.vue')['default']
    ReviewQuick: typeof import('./src/components/review/ReviewQuick.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/common/TabBar.vue')['default']
    TrendChart: typeof import('./src/components/stats/TrendChart.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTag: typeof import('vant/es')['Tag']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
